weather=input("what is the weather for you today sunny, rainy, cloudy, or stormy? ")#asking weather
mood=input("what is your mood today happy, sad , angry, normal? ")#asking mood
if weather=="sunny":
    print("Nice! you should have a walk outside")#replies
elif weather=="rainy":
    print("Oh make sure to use an umbrella")
elif weather=="cloudy":
    print("Oh perfect temperature not too hot or cold!")
elif weather=="stormy":
    print("Make sure to stay inside since its dangerous!")

if mood==("happy"):#replies for moods
    import turtle
    t=turtle.Turtle()
    t.speed(0)
    t.color("yellow")
    t.begin_fill()
    t.goto(0,0)
    t.circle(150)
    t.end_fill()
    t.goto(0,200)
    t.left(180)
    t.forward(70)
    t.color("black")
    t.begin_fill()
    t.circle(30)
    t.end_fill()
    t.penup()
    t.goto(0,200)
    t.backward(70)
    t.color("black")
    t.begin_fill()
    t.pendown()
    t.circle(30)
    t.end_fill()
    t.penup()
    t.goto(-100,100)
    t.left(110)
    t.pendown()
    t.circle(100,150)
    t.hideturtle()
    turtle.done()
elif mood==("sad"):
    import turtle
    t=turtle.Turtle()
    t.speed(0)
    t.color("blue")
    t.begin_fill()
    t.goto(0,0)
    t.circle(150)
    t.end_fill()
    t.penup()
    t.goto(0,200)
    t.left(180)
    t.pendown()
    t.forward(70)
    t.color("black")
    t.begin_fill()
    t.circle(30)
    t.end_fill()
    t.penup()
    t.goto(0,200)
    t.backward(70)
    t.color("black")
    t.begin_fill()
    t.pendown()
    t.circle(30)
    t.end_fill()
    t.penup()
    t.goto(90,50)
    t.left(110)
    t.pendown()
    t.color("black")
    t.circle(-90,-140)
    t.hideturtle()
    turtle.done()
elif mood==("angry"):
    import turtle
    t=turtle.Turtle()
    t.speed(0)
    t.color("red")
    t.begin_fill()
    t.goto(0,0)
    t.circle(150)
    t.end_fill()
    t.penup()
    t.goto(0,200)
    t.left(180)
    t.pendown()
    t.forward(70)
    t.color("black")
    t.begin_fill()
    t.circle(30)
    t.end_fill()
    t.penup()
    t.goto(0,200)
    t.backward(70)
    t.color("black")
    t.begin_fill()
    t.pendown()
    t.circle(30)
    t.end_fill()
    t.penup()
    t.goto(90,50)
    t.left(110)
    t.pendown()
    t.color("black")
    t.circle(-90,-140)
    t.penup()
    t.goto(-100,250)
    t.pendown()
    t.left(-110)
    t.fd(100)
    t.penup()
    t.goto(100,250)
    t.left(-100)
    t.pendown()
    t.fd(100)
    t.hideturtle()
    turtle.done()
elif mood==("normal"):
    import turtle
    t=turtle.Turtle()
    t.speed(0)
    t.color("yellow")
    t.begin_fill()
    t.goto(0,0)
    t.circle(150)
    t.end_fill()
    t.goto(0,200)
    t.left(180)
    t.forward(70)
    t.color("black")
    t.begin_fill()
    t.circle(30)
    t.end_fill()
    t.penup()
    t.goto(0,200)
    t.backward(70)
    t.color("black")
    t.begin_fill()
    t.pendown()
    t.circle(30)
    t.end_fill()
    t.penup()
    t.goto(-100,70)
    t.right(180)
    t.pendown()
    t.fd(215)
    t.hideturtle()
    turtle.done()

    
